language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

before_install:
  - pecl install ds
  - pecl install swoole
  - phpenv config-add ./test/travis/php.ini

install:
  - composer install --no-interaction

script:
  - composer cs-check
  - composer license-check
  - composer phpstan
  - composer phpunit-coverage

after_script:
  - composer coveralls

notifications:
  email: false
